version: "3"
services:
  jupyterhub_admin:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    container_name: jupyterhub_admin
    volumes:
      - ./src:/app
    command: python manage.py runserver 0.0.0.0:8000
